name: a_dokter_register
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  fluttertoast: ^8.2.2
  google_fonts: ^3.0.1
  email_validator: ^2.1.17
  flutter_html: ^0.11.1
  flutter_webview_plugin: ^0.4.0
  url_launcher: ^6.1.5
  webview_flutter: ^4.2.2
  badges: ^2.0.3
  flutter_rating_bar: ^4.0.1
  package_info_plus: ^1.4.2
  flutter_dash: ^0.0.1
  dropdown_button2: ^1.4.0
  qr_code_scanner: ^1.0.1
  im_stepper: ^0.1.3
  image_picker: ^0.8.5+3
  coordinator_layout: ^1.0.0+1
  flutter_staggered_grid_view: ^0.6.2
  google_maps_flutter: ^2.2.0
  build_runner: ^2.2.0
  get_storage: ^2.1.1
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  http: ^0.13.5
  google_api_headers: ^1.3.0
  # flutter_google_places: ^0.3.0
  awesome_drawer_bar: ^1.0.0
  autocomplete_textfield: ^2.0.1
  awesome_dialog: ^2.2.0
  provider: ^6.0.3
  speech_to_text: ^6.1.1
  highlight_text: ^1.6.0
  flutter_tts: ^3.2.2
  avatar_glow: ^2.0.2
  calendar_timeline: ^1.1.1
  carousel_slider: ^4.1.1
  hive: ^2.2.3
  
  hive_flutter: ^1.1.0
  ##
  dio: ^4.0.6
  flutter_launcher_icons: ^0.10.0
  flutter_icons_null_safety: ^1.1.0
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.1
  horizontal_calendar: ^1.1.2
  lottie: ^1.2.1
  dropdown_search: ^5.0.6
  flutter_easyloading: ^3.0.0
  text_scroll: ^0.1.2
  animations: ^2.0.7
  flutter_staggered_animations: ^1.1.1
  flutter_animated_dialog: ^2.0.1
  quickalert: ^1.0.1
  buttons_tabbar: ^1.3.6
  flutter_svg: ^1.1.0
  custom_sliding_segmented_control: ^1.7.4
  bubble_tab_indicator: ^0.1.6
  syncfusion_flutter_charts: ^21.1.38
  appbar_animated: ^0.0.3
  animated_bottom_navigation_bar: ^1.2.0
  font_awesome_flutter:
  flutter: 
    sdk: flutter
  fl_chart: ^0.62.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/

